version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./src/db/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
    networks:
      - backend

networks:
  backend:
    driver: bridge